### ISSUE TITLE
How to use it NOW ? 

### ISSUE THREAD

**Issue by kaiyes** [Neobii/files-gridfs-autoform-example#1]
Hi, 

Just followed the trail and ended up here. So is there any way to use this right now with autoform ? I am running a production app and looking for a pdf file upload download solution. 

And what about using it with quick - forms ? Does that work ? 

Thanks

**Comment by Neobii** [comment]
It's still a WIP.  The autoform integration is pretty manual at this point,
but I used it on some of the super critical file uploads I was needing.
I'm working on it right now and trying to define it as a field input, check
this branch
https://github.com/Neobii/files-gridfs-autoform-example/tree/autoform-field
where I'm trying to add it as an input type, pull requests accepted :).

**Comment by kaiyes** [comment]
alright checking it now ! As long as I can easily upload and download just one pdf files/user I am happy. I doubt I will be able to send pull requests, but I am here for testing if you need it. 

And to use it do I need be on latest meteor ?

**Comment by Neobii** [comment]
Have you tried yogiben:autoform-file?  If you haven't that'd be the first
thing to try.

**Comment by kaiyes** [comment]
I know about yogibens package. I am trying avoid uploading to my server. Rather I want to upload to somewhere else like s3 or dropbox. But thanks.

**Comment by Neobii** [comment]
Oh, this example uses gridFS, I haven't even tried using with other stuff,
but it seems like the gridFS stuff in my code is easily removed / replaced.

**Comment by Neobii** [comment]
I just released it with autoform integration and put some issues up giving hints about the current limitations.  Unfortunately, this is where I leave off for now.  I'll probably be able to continue work later on this week.

**Comment by kaiyes** [comment]
awesome. Thanks for helping
